[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): pypi.io:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://pypi.io:443 "GET /pypi/mpi4py_test/json HTTP/1.1" 301 122
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): pypi.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://pypi.org:443 "GET /pypi/mpi4py-test/json HTTP/1.1" 200 2127
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://files.pythonhosted.org:443 "GET /packages/19/e0/568d6a015728d1d56cd367d7a647f7ef203cec160e764299115516571a8e/mpi4py_test-0.0.10.tar.gz HTTP/1.1" 200 7137
[32mINFO    [0m conda_build.metadata:metadata.py:854 Attempting to finalize metadata for mpi4py_test
[33mWARNING [0m conda_build.render:render.py:625 Returning non-final recipe for mpi4py_test-0.0.10-py39_0; one or more dependencies was unsatisfiable:
[33mWARNING [0m conda_build.render:render.py:630 Host: tzdata, tzdata, tzdata, libgfortran-ng, libgfortran-ng, wheel, wheel, python, python, python, python, python, _openmp_mutex, _openmp_mutex, feature:/linux-64::__glibc, feature:|@/linux-64::__glibc, __glibc, __glibc