2023-01-06T16:25:27 Error extracting another_bad_package.conda
Traceback (most recent call last):
  File "C:\Users\runneradmin\Miniconda3\lib\site-packages\conda_index\index\sqlitecache.py", line 216, in _extract_to_cache
    index_json = self.extract_to_cache_unconditional(
  File "C:\Users\runneradmin\Miniconda3\lib\site-packages\conda_index\index\sqlitecache.py", line 251, in extract_to_cache_unconditional
    package_stream = iter(package_streaming.stream_conda_info(abs_fn))
  File "C:\Users\runneradmin\Miniconda3\lib\site-packages\conda_package_streaming\package_streaming.py", line 75, in stream_conda_info
    return stream_conda_component(filename, fileobj, component)
  File "C:\Users\runneradmin\Miniconda3\lib\site-packages\conda_package_streaming\package_streaming.py", line 98, in stream_conda_component
    zf = zipfile.ZipFile(fileobj or filename)
  File "C:\Users\runneradmin\Miniconda3\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\runneradmin\Miniconda3\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
2023-01-06T16:25:27 Error extracting bad_package.tar.bz2
Traceback (most recent call last):
  File "C:\Users\runneradmin\Miniconda3\lib\site-packages\conda_index\index\sqlitecache.py", line 216, in _extract_to_cache
    index_json = self.extract_to_cache_unconditional(
  File "C:\Users\runneradmin\Miniconda3\lib\site-packages\conda_index\index\sqlitecache.py", line 252, in extract_to_cache_unconditional
    for tar, member in package_stream:
  File "C:\Users\runneradmin\Miniconda3\lib\site-packages\conda_package_streaming\package_streaming.py", line 50, in tar_generator
    with tarfile_open(fileobj=fileobj, mode="r|") as tar:
  File "C:\Users\runneradmin\Miniconda3\lib\tarfile.py", line 1664, in open
    t = cls(name, filemode, stream, **kwargs)
  File "C:\Users\runneradmin\Miniconda3\lib\tarfile.py", line 1542, in __init__
    self.firstmember = self.next()
  File "C:\Users\runneradmin\Miniconda3\lib\tarfile.py", line 2377, in next
    raise e
  File "C:\Users\runneradmin\Miniconda3\lib\tarfile.py", line 2350, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "C:\Users\runneradmin\Miniconda3\lib\tarfile.py", line 1122, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "C:\Users\runneradmin\Miniconda3\lib\tarfile.py", line 522, in read
    buf = self._read(size)
  File "C:\Users\runneradmin\Miniconda3\lib\tarfile.py", line 530, in _read
    return self.__read(size)
  File "C:\Users\runneradmin\Miniconda3\lib\tarfile.py", line 560, in __read
    buf = self.fileobj.read(self.bufsize)
  File "C:\Users\runneradmin\Miniconda3\lib\bz2.py", line 164, in read
    return self._buffer.read(size)
  File "C:\Users\runneradmin\Miniconda3\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "C:\Users\runneradmin\Miniconda3\lib\_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream
ERROR conda_index.index:extract_subdir_to_cache(791): Package at D:\a\conda-build\conda-build\tests\index_data\corrupt\noarch\another_bad_package.conda did not contain valid index.json data.  Please check the file and remove/redownload if necessary to obtain a valid package.
ERROR conda_index.index:extract_subdir_to_cache(791): Package at D:\a\conda-build\conda-build\tests\index_data\corrupt\noarch\bad_package.tar.bz2 did not contain valid index.json data.  Please check the file and remove/redownload if necessary to obtain a valid package.
2023-01-06T16:25:28 Subdir: noarch Gathering repodata
2023-01-06T16:25:28 noarch Writing pre-patch repodata
2023-01-06T16:25:28 noarch Applying patch instructions
2023-01-06T16:25:28 noarch Writing patched repodata
2023-01-06T16:25:28 noarch Building current_repodata subset
2023-01-06T16:25:28 noarch Writing current_repodata subset
2023-01-06T16:25:28 noarch Writing index HTML
