{"uid":"cc3d424dbcec96a6","name":"test_variant_with_ignore_numpy_version_reduces_matrix","fullName":"tests.test_variants#test_variant_with_ignore_numpy_version_reduces_matrix","historyId":"20be92025da8fed1321d1f318c32bbaf","time":{"start":1673033285257,"stop":1673033285589,"duration":332},"status":"skipped","statusMessage":"XFAIL Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(\n\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab55a1f90>, '_meta_path': '/home/ru...mkl', 'numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab55a1f90>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'target_platform': 'linux-64', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab6e6bdf0>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'target_platform': 'linux-64', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab7a2be50>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'target_platform': 'linux-64', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab6e68d30>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'target_platform': 'linux-64', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/conda-build/conda-build/tests/test_variants.py\", line 119, in test_variant_with_ignore_numpy_version_reduces_matrix\n    assert len(metadata) == 2, metadata\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab55a1f90>, '_meta_path': '/home/ru...mkl', 'numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab55a1f90>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'target_platform': 'linux-64', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab6e6bdf0>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'target_platform': 'linux-64', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab7a2be50>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'target_platform': 'linux-64', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f8ab6e68d30>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'target_platform': 'linux-64', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1673030655855,"stop":1673030655856,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"tmp_path","time":{"start":1673033285252,"stop":1673033285254,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"tmpdir","time":{"start":1673033285254,"stop":1673033285254,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_workdir","time":{"start":1673033285254,"stop":1673033285254,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_config","time":{"start":1673033285254,"stop":1673033285255,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"numpy_version_ignored","time":{"start":1673033285255,"stop":1673033285255,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"default_testing_config","time":{"start":1673033285255,"stop":1673033285255,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"monkeypatch","time":{"start":1673033285255,"stop":1673033285255,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"afterStages":[{"name":"monkeypatch::0","time":{"start":1673033285593,"stop":1673033285593,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_workdir::return_to_saved_path","time":{"start":1673033285594,"stop":1673033285594,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_variants"},{"name":"host","value":"fv-az436-279"},{"name":"thread","value":"3836-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_variants"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(reason='Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(')"]},"source":"cc3d424dbcec96a6.json","parameterValues":[]}