[35mDEBUG   [0m urllib3.util.retry:retry.py:594 Incremented Retry for (url='/pkgs/free/win-64/affine-2.0.0-py27_0.tar.bz2'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Read timed out. (read timeout=60.0)")': /pkgs/free/win-64/affine-2.0.0-py27_0.tar.bz2
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1007 Starting new HTTPS connection (5): repo.anaconda.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://repo.anaconda.com:443 "GET /pkgs/free/win-64/affine-2.0.0-py27_0.tar.bz2 HTTP/1.1" 200 20579