{"uid":"1b82269ce8388e44","name":"test_build_with_activate_does_activate","fullName":"tests.test_api_build#test_build_with_activate_does_activate","historyId":"574b6dfbccd7437492e0ab28d439ba60","time":{"start":1669037841104,"stop":1669037862169,"duration":21065},"status":"skipped","statusMessage":"XFAIL Long PATHs make activation fail with obscure messages\n\nsubprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.","statusTrace":"Traceback (most recent call last):\n  File \"D:\\a\\conda-build\\conda-build\\tests\\test_api_build.py\", line 284, in test_build_with_activate_does_activate\n    api.build(os.path.join(metadata_dir, '_set_env_var_activate_build'), activate=True,\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\api.py\", line 180, in build\n    return build_tree(\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\build.py\", line 3094, in build_tree\n    packages_from_this = build(metadata, stats,\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\build.py\", line 2177, in build\n    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\windows.py\", line 302, in build\n    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\utils.py\", line 402, in check_call_env\n    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\utils.py\", line 382, in _func_defaulting_env_to_os_environ\n    raise subprocess.CalledProcessError(proc.returncode, _args)\nsubprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"skipped","statusMessage":"XFAIL Long PATHs make activation fail with obscure messages\n\nsubprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.","statusTrace":"Traceback (most recent call last):\n  File \"D:\\a\\conda-build\\conda-build\\tests\\test_api_build.py\", line 284, in test_build_with_activate_does_activate\n    api.build(os.path.join(metadata_dir, '_set_env_var_activate_build'), activate=True,\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\api.py\", line 180, in build\n    return build_tree(\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\build.py\", line 3094, in build_tree\n    packages_from_this = build(metadata, stats,\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\build.py\", line 2177, in build\n    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\windows.py\", line 302, in build\n    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\utils.py\", line 402, in check_call_env\n    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\utils.py\", line 382, in _func_defaulting_env_to_os_environ\n    raise subprocess.CalledProcessError(proc.returncode, _args)\nsubprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.","steps":[],"attachments":[{"uid":"682b78251f1f2982","name":"log","source":"682b78251f1f2982.txt","type":"text/plain","size":290},{"uid":"1a7975f5be1d43f2","name":"stdout","source":"1a7975f5be1d43f2.txt","type":"text/plain","size":12137}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.xfail(True, reason='Long PATHs make activation fail with obscure messages')"},{"name":"tag","value":"serial"},{"name":"tag","value":"sanity"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_api_build"},{"name":"host","value":"fv-az478-485"},{"name":"thread","value":"528-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_api_build"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":0,"unknown":0,"total":2},"items":[{"uid":"81975da435e3b5ab","status":"skipped","statusDetails":"XFAIL Long PATHs make activation fail with obscure messages\n\nsubprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.","time":{"start":1668036832662,"stop":1668036853142,"duration":20480}}]},"tags":["serial","sanity","@pytest.mark.xfail(True, reason='Long PATHs make activation fail with obscure messages')"]},"source":"1b82269ce8388e44.json","parameterValues":[]}