{"uid":"40a1fe3ee4621f2","name":"test_copy_read_only_file_with_xattr","fullName":"tests.test_api_build#test_copy_read_only_file_with_xattr","historyId":"8f800bd25b9f9b621339dcc17d2130a9","time":{"start":1673020897910,"stop":1673020897926,"duration":16},"status":"skipped","statusMessage":"XFAIL reason: setfattr not possible in /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build, see https://stackoverflow.com/a/46598063\n\n_pytest.outcomes.XFailed: setfattr not possible in /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build, see https://stackoverflow.com/a/46598063","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/conda-build/conda-build/tests/test_api_build.py\", line 1110, in test_copy_read_only_file_with_xattr\n    subprocess.check_call(f'setfattr -n user.attrib -v somevalue {ro_file}', shell=True)\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/subprocess.py\", line 363, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command 'setfattr -n user.attrib -v somevalue /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build/_xattr_copy/mode_400_file' returned non-zero exit status 127.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/conda-build/conda-build/tests/test_api_build.py\", line 1113, in test_copy_read_only_file_with_xattr\n    testing_homedir))\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/_pytest/outcomes.py\", line 252, in xfail\n    raise XFailed(reason)\n_pytest.outcomes.XFailed: setfattr not possible in /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build, see https://stackoverflow.com/a/46598063","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1673019024318,"stop":1673019024319,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"tmp_path","time":{"start":1673020897906,"stop":1673020897907,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"tmpdir","time":{"start":1673020897907,"stop":1673020897907,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_workdir","time":{"start":1673020897907,"stop":1673020897907,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_config","time":{"start":1673020897907,"stop":1673020897908,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"default_testing_config","time":{"start":1673020897908,"stop":1673020897908,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"monkeypatch","time":{"start":1673020897908,"stop":1673020897908,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_homedir","time":{"start":1673020897908,"stop":1673020897909,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL reason: setfattr not possible in /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build, see https://stackoverflow.com/a/46598063\n\n_pytest.outcomes.XFailed: setfattr not possible in /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build, see https://stackoverflow.com/a/46598063","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/conda-build/conda-build/tests/test_api_build.py\", line 1110, in test_copy_read_only_file_with_xattr\n    subprocess.check_call(f'setfattr -n user.attrib -v somevalue {ro_file}', shell=True)\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/subprocess.py\", line 363, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command 'setfattr -n user.attrib -v somevalue /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build/_xattr_copy/mode_400_file' returned non-zero exit status 127.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/conda-build/conda-build/tests/test_api_build.py\", line 1113, in test_copy_read_only_file_with_xattr\n    testing_homedir))\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/_pytest/outcomes.py\", line 252, in xfail\n    raise XFailed(reason)\n_pytest.outcomes.XFailed: setfattr not possible in /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build, see https://stackoverflow.com/a/46598063","steps":[],"attachments":[{"uid":"9bb825bf9b0038d0","name":"stderr","source":"9bb825bf9b0038d0.txt","type":"text/plain","size":32}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"testing_homedir::return_to_saved_path","time":{"start":1673020897930,"stop":1673020897930,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"monkeypatch::0","time":{"start":1673020897931,"stop":1673020897931,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_workdir::return_to_saved_path","time":{"start":1673020897932,"stop":1673020897932,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.skipif(False, reason='xattr code written here is specific to linux')"},{"name":"tag","value":"serial"},{"name":"tag","value":"sanity"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_api_build"},{"name":"host","value":"fv-az559-855"},{"name":"thread","value":"3739-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_api_build"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":0,"unknown":0,"total":2},"items":[{"uid":"bdae626d17c27fd2","status":"skipped","statusDetails":"XFAIL reason: setfattr not possible in /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build, see https://stackoverflow.com/a/46598063\n\n_pytest.outcomes.XFailed: setfattr not possible in /home/runner/test_copy_read_only_file_with_0/serial/_temp/pytest.conda-build, see https://stackoverflow.com/a/46598063","time":{"start":1673016539983,"stop":1673016539997,"duration":14}}]},"tags":["@pytest.mark.skipif(False, reason='xattr code written here is specific to linux')","serial","sanity"]},"source":"40a1fe3ee4621f2.json","parameterValues":[]}