[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:232 Starting new HTTP connection (1): repo.anaconda.com:80
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 http://repo.anaconda.com:80 "GET /pkgs/free/win-64/cryptography-1.8.1-py36_0.tar.bz2 HTTP/1.1" 301 None
[35mDEBUG   [0m urllib3.util.retry:retry.py:594 Incremented Retry for (url='/pkgs/free/win-64/cryptography-1.8.1-py36_0.tar.bz2'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Read timed out. (read timeout=60.0)")': /pkgs/free/win-64/cryptography-1.8.1-py36_0.tar.bz2
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1007 Starting new HTTPS connection (2): repo.anaconda.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://repo.anaconda.com:443 "GET /pkgs/free/win-64/cryptography-1.8.1-py36_0.tar.bz2 HTTP/1.1" 200 358458