[32mINFO    [0m conda_build.inspect_pkg:inspect_pkg.py:155 ######## Testing platform osx-64 ########
[35mDEBUG   [0m urllib3.util.retry:retry.py:594 Incremented Retry for (url='/conda-team/osx-64/repodata.json'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out. (read timeout=60.0)")': /conda-team/osx-64/repodata.json
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1007 Starting new HTTPS connection (2): conda.anaconda.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://conda.anaconda.org:443 "GET /conda-team/osx-64/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://conda.anaconda.org:443 "GET /conda-team/noarch/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://conda.anaconda.org:443 "GET /conda-team/linux-32/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://conda.anaconda.org:443 "GET /conda-team/linux-64/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://conda.anaconda.org:443 "GET /conda-team/win-32/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://conda.anaconda.org:443 "GET /conda-team/win-64/repodata.json HTTP/1.1" 200 502