{"uid":"ca70d2275130348f","name":"test_legacy_noarch_python","fullName":"tests.test_api_build#test_legacy_noarch_python","historyId":"feb96acc35227ee5eec272cc2f5d058b","time":{"start":1669034508707,"stop":1669034528339,"duration":19632},"status":"skipped","statusMessage":"XFAIL parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.\n\nAttributeError: 'dict' object has no attribute 'subdir'","statusTrace":"Traceback (most recent call last):\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/conda_verify/checks.py\", line 87, in __init__\n    with open(os.path.join(self.tmpdir, 'info', 'paths.json')) as f:\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmkfcn82p/info/paths.json'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/conda-build/conda-build/tests/test_api_build.py\", line 824, in test_legacy_noarch_python\n    config=testing_config)[0]\n  File \"/home/runner/work/conda-build/conda-build/conda_build/api.py\", line 189, in build\n    variants=variants\n  File \"/home/runner/work/conda-build/conda-build/conda_build/build.py\", line 3099, in build_tree\n    notest=notest,\n  File \"/home/runner/work/conda-build/conda-build/conda_build/build.py\", line 2369, in build\n    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)\n  File \"/home/runner/work/conda-build/conda-build/conda_build/build.py\", line 1712, in bundle_conda\n    exit_on_error=metadata.config.exit_on_verify_error)\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/conda_verify/verify.py\", line 20, in verify_package\n    package_check = CondaPackageCheck(path_to_package)\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/conda_verify/checks.py\", line 92, in __init__\n    assert self.info.subdir == 'noarch'\nAttributeError: 'dict' object has no attribute 'subdir'","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1669034325494,"stop":1669034325495,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0},{"name":"tmp_path","time":{"start":1669034508704,"stop":1669034508704,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0},{"name":"tmpdir","time":{"start":1669034508705,"stop":1669034508705,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0},{"name":"testing_workdir","time":{"start":1669034508705,"stop":1669034508705,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0},{"name":"testing_config","time":{"start":1669034508705,"stop":1669034508705,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0}],"testStage":{"status":"skipped","statusMessage":"XFAIL parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.\n\nAttributeError: 'dict' object has no attribute 'subdir'","statusTrace":"Traceback (most recent call last):\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/conda_verify/checks.py\", line 87, in __init__\n    with open(os.path.join(self.tmpdir, 'info', 'paths.json')) as f:\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmkfcn82p/info/paths.json'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/conda-build/conda-build/tests/test_api_build.py\", line 824, in test_legacy_noarch_python\n    config=testing_config)[0]\n  File \"/home/runner/work/conda-build/conda-build/conda_build/api.py\", line 189, in build\n    variants=variants\n  File \"/home/runner/work/conda-build/conda-build/conda_build/build.py\", line 3099, in build_tree\n    notest=notest,\n  File \"/home/runner/work/conda-build/conda-build/conda_build/build.py\", line 2369, in build\n    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)\n  File \"/home/runner/work/conda-build/conda-build/conda_build/build.py\", line 1712, in bundle_conda\n    exit_on_error=metadata.config.exit_on_verify_error)\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/conda_verify/verify.py\", line 20, in verify_package\n    package_check = CondaPackageCheck(path_to_package)\n  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/conda_verify/checks.py\", line 92, in __init__\n    assert self.info.subdir == 'noarch'\nAttributeError: 'dict' object has no attribute 'subdir'","steps":[],"attachments":[{"uid":"1a2c04370ac7a39a","name":"log","source":"1a2c04370ac7a39a.txt","type":"text/plain","size":190},{"uid":"89a720336770a584","name":"stdout","source":"89a720336770a584.txt","type":"text/plain","size":4006},{"uid":"4289aaf8a154fddb","name":"stderr","source":"4289aaf8a154fddb.txt","type":"text/plain","size":474}],"parameters":[],"shouldDisplayMessage":true,"hasContent":true,"stepsCount":0,"attachmentsCount":3},"afterStages":[{"name":"testing_workdir::return_to_saved_path","time":{"start":1669034528348,"stop":1669034528348,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(True, reason='parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.')"},{"name":"tag","value":"sanity"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_api_build"},{"name":"host","value":"fv-az626-399"},{"name":"thread","value":"3558-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_api_build"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":0,"unknown":0,"total":2},"items":[{"uid":"23ef99a57293e951","status":"skipped","statusDetails":"XFAIL parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.\n\nAttributeError: 'dict' object has no attribute 'subdir'","time":{"start":1668034263719,"stop":1668034286199,"duration":22480}}]},"tags":["@pytest.mark.xfail(True, reason='parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.')","sanity"]},"source":"ca70d2275130348f.json","parameterValues":[]}