[32mINFO    [0m conda_build.inspect_pkg:inspect_pkg.py:155 ######## Testing platform osx-64 ########
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:273 Resetting dropped connection: conda.anaconda.org
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://conda.anaconda.org:443 "GET /conda-team/osx-64/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://conda.anaconda.org:443 "GET /conda-team/noarch/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://conda.anaconda.org:443 "GET /conda-team/linux-32/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://conda.anaconda.org:443 "GET /conda-team/linux-64/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://conda.anaconda.org:443 "GET /conda-team/win-32/repodata.json HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://conda.anaconda.org:443 "GET /conda-team/win-64/repodata.json HTTP/1.1" 200 502